# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170412_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='store.CartItem'),
        ),
    ]
