# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
